# Generated by Django 6.1 on 2026-08-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_path', models.CharField(max_length=1000)),
                ('module_type', models.CharField(choices=[('class', 'Class'), ('file', 'File')], max_length=10)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_modules', to='projects.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metrics.softwaremodule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='softwaremodule',
            constraint=models.UniqueConstraint(fields=('analysis_run', 'module_path'), name='unique_module_path_per_analysis_run'),
        ),
        migrations.AddConstraint(
            model_name='softwaremetric',
            constraint=models.UniqueConstraint(fields=('module', 'metric_name'), name='unique_metric_name_per_module'),
        ),
    ]
